object Versions {
    const val gradlePlugin = "7.2.0"
    const val kotlin = "1.6.10"
    const val androidCoreKtx = "1.8.0"
    const val appCompat = "1.4.2"
    const val material = "1.6.1"
    const val jUnit = "4.13.2"
    const val androidJUnit = "1.1.3"
    const val expresso = "3.4.0"
    const val cameraX = "1.1.0-rc01"
    const val androidxLifecycleKtx = "2.3.1"
    const val timber = "4.7.1"
    const val concurrentFuture = "1.1.0"
    const val compose = "1.1.1"
    const val composeActivity = "1.3.0-beta02"
    const val composeNavigation = "2.4.2"
    const val accompanist = "0.23.1"
    const val coil = "2.1.0"
}